
services:
  client:
    depends_on:
      - server
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    container_name: link_vault_frontend
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - '3000:3000'
    working_dir: /app
    stdin_open: true

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: link_vault-backend
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - '8000:8000'

  remitsafe-server:
    build:
      context: ./
      dockerfile: ./remitsafe/backend/Dockerfile
    container_name: remitsafe-backend
    volumes:
      - "./remitsafe/backend:/app"
      - "/app/node_modules"
    ports:
      - '3001:3001'

  remitsafe-client:
    depends_on:
      - remitsafe-server
    build:
      context: ./
      dockerfile: ./remitsafe/frontend/Dockerfile
    container_name: remitsafe-frontend
    volumes:
      - "./remitsafe/frontend:/app"
      - "/app/node_modules"
    ports:
      - '8001:8001'
    working_dir: /app
    stdin_open: true
